# HW05 - Exploring Trees/Graphs

YOUR NAME: Muaz Ahmad

In [1]:
# here is a list of edges:
T = [('Bob','Eve'),('Alice','Carol'),('Eve','Frank'),('Alice','Doug'),('Frank','Ginger'),\
         ('Eve','Howard'),('Carol','Irene'),('Frank','Jeff'),('Doug','Kathy'),('Bob','Luis'),\
         ('Alice','Bob'),('Bob','Mabel'),('Ginger','Norm'),('Howard','Oprah'),('Carol','Peter'),\
         ('Kathy','Queen'),('Mabel','Ursala'),('Luis','Ronald'),('Ginger','Sarah'),('Irene','Tom'),\
         ('Jeff','Vince'),('Peter','Wanda'),('Oprah','Xanthia'),('Norm','Yaakov'),('Luis','Zandra')]

print ('T has',len(T),'edges')
vertices = set()
for edge in T:
    s,t = edge
    vertices.add(s)
    vertices.add(t)
print ('T has',len(vertices),'vertices')
print (vertices)

T has 25 edges
T has 26 vertices
{'Norm', 'Yaakov', 'Jeff', 'Peter', 'Vince', 'Mabel', 'Ursala', 'Bob', 'Sarah', 'Ginger', 'Queen', 'Irene', 'Zandra', 'Kathy', 'Doug', 'Ronald', 'Howard', 'Frank', 'Wanda', 'Luis', 'Alice', 'Xanthia', 'Oprah', 'Carol', 'Tom', 'Eve'}


So this could be a tree. Now lets compute the number of parents for each vertex. The result confirms that we indeed have a tree and that the root is Alice (right?). Yes Alice is the root because it has no parent and all vertices have a path from Alice

In [2]:
np = {}
for v in vertices:
    np[v] = 0
for parent,child in T:
    np[child] += 1
print (np)

{'Norm': 1, 'Yaakov': 1, 'Jeff': 1, 'Peter': 1, 'Vince': 1, 'Mabel': 1, 'Ursala': 1, 'Bob': 1, 'Sarah': 1, 'Ginger': 1, 'Queen': 1, 'Irene': 1, 'Zandra': 1, 'Kathy': 1, 'Doug': 1, 'Ronald': 1, 'Howard': 1, 'Frank': 1, 'Wanda': 1, 'Luis': 1, 'Alice': 0, 'Xanthia': 1, 'Oprah': 1, 'Carol': 1, 'Tom': 1, 'Eve': 1}


We now construct a dictionary of pairs (p,c) where p is the parent of the list of children c

In [3]:
family_tree = {}
for v in vertices:
    family_tree[v] = []
for p,c in T:
    family_tree[p].append(c)
for p in family_tree:
    print (p,family_tree[p])
print (family_tree)

Norm ['Yaakov']
Yaakov []
Jeff ['Vince']
Peter ['Wanda']
Vince []
Mabel ['Ursala']
Ursala []
Bob ['Eve', 'Luis', 'Mabel']
Sarah []
Ginger ['Norm', 'Sarah']
Queen []
Irene ['Tom']
Zandra []
Kathy ['Queen']
Doug ['Kathy']
Ronald []
Howard ['Oprah']
Frank ['Ginger', 'Jeff']
Wanda []
Luis ['Ronald', 'Zandra']
Alice ['Carol', 'Doug', 'Bob']
Xanthia []
Oprah ['Xanthia']
Carol ['Irene', 'Peter']
Tom []
Eve ['Frank', 'Howard']
{'Norm': ['Yaakov'], 'Yaakov': [], 'Jeff': ['Vince'], 'Peter': ['Wanda'], 'Vince': [], 'Mabel': ['Ursala'], 'Ursala': [], 'Bob': ['Eve', 'Luis', 'Mabel'], 'Sarah': [], 'Ginger': ['Norm', 'Sarah'], 'Queen': [], 'Irene': ['Tom'], 'Zandra': [], 'Kathy': ['Queen'], 'Doug': ['Kathy'], 'Ronald': [], 'Howard': ['Oprah'], 'Frank': ['Ginger', 'Jeff'], 'Wanda': [], 'Luis': ['Ronald', 'Zandra'], 'Alice': ['Carol', 'Doug', 'Bob'], 'Xanthia': [], 'Oprah': ['Xanthia'], 'Carol': ['Irene', 'Peter'], 'Tom': [], 'Eve': ['Frank', 'Howard']}


In [4]:
print (5*"Hello!")


Hello!Hello!Hello!Hello!Hello!


In [5]:
# A recursive Depth-First traversal of a tree defined by a dictionary
def print_tree_depth_first(parent, dictionary, level=0):
    print (level*'  ', parent)
    children = dictionary[parent]
    for child in children:
        print_tree_depth_first(child, dictionary, level+1)

root = 'Alice'
print_tree_depth_first(root, family_tree)

 Alice
   Carol
     Irene
       Tom
     Peter
       Wanda
   Doug
     Kathy
       Queen
   Bob
     Eve
       Frank
         Ginger
           Norm
             Yaakov
           Sarah
         Jeff
           Vince
       Howard
         Oprah
           Xanthia
     Luis
       Ronald
       Zandra
     Mabel
       Ursala


## Question 1
extend the breadth-first traversal to include the generation, so that the output is like below. Do this by storing a tuple with generation and node in the queue.

In [6]:
from collections import deque 

# breadth-first traversal using a queue
def print_tree_breath_first(root, dictionary):
    Q = deque()
    generation = 1
    former = 0
    Q.append([root,generation])
    level = []
    while len(Q)>0:
        p,g = Q.popleft()
        if g == former:
             print ('\t',p, end='')
        else:
            print()
            print (g, ':', p, end='')
        former = g
       
        
        children = dictionary[p]
        g = g + 1
        
        for child in children:
            Q.append([child,g])

print_tree_breath_first("Alice", family_tree)


1 : Alice
2 : Carol	 Doug	 Bob
3 : Irene	 Peter	 Kathy	 Eve	 Luis	 Mabel
4 : Tom	 Wanda	 Queen	 Frank	 Howard	 Ronald	 Zandra	 Ursala
5 : Ginger	 Jeff	 Oprah
6 : Norm	 Sarah	 Vince	 Xanthia
7 : Yaakov

## Question 2
Write a function that checks if for the given directed graph (given by a list of edges E) root is connected to every other vertex.

In [7]:

    
    
def all_connected_to(E, root):
    """ return true if you can reach all nodes in the graph given
    by a list of edges E can be reached by root """
    
    # start by constructing set of vertices and a dictionary for looking up children
    vertices = set()
    connected = {}
    for u,v in E:
        vertices.add(u)
        vertices.add(v)
        connected[u] = []
        connected[v] = []
   
    for u,v in E:
        connected[u].append(v)
    for i in vertices:
        Q = deque()
        Q.append(root)
        if i != root:
            #print (i)
            found = False
            g =Q.popleft()
            #print (i, len(Q),g)
            children = connected[g]
            if i in children:
                found = True
                break
            else:
                for n in children:
                    Q.append(n) 
            while len(Q)>0:
                g =Q.popleft()
                if g == root:
                    break
                #print (i, len(Q),g)
                children = connected[g]
                if i in children:
                    found = True
                    break
                else:
                    for n in children:
                        Q.append(n)
            if found == False:
                return False   
    return True
            
        
    

In [8]:
G = [("A","B"), ("B","C")]
print (all_connected_to(G, "A"))
G2 = [("1","2"), ("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G2, "A"))
print (all_connected_to(G2, "1"))
G3 = [("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G3, "C"))
# and our graph from above?
print (all_connected_to(T, "Alice"))

True
False
True
True
True


## Question 3
We now treat the the graph T from above as undirected (edges going in both directions) and construct a tree rooted in Bob. The tree will contain edges from a vertex to the parent and direct children. The result will tell us how far removed the vertices from our root Bob are.

In [9]:
root = 'Bob'

family_dict = {}
tree = {}
visited = {}
for vertex in vertices:
    family_dict[vertex] = []
    tree[vertex] = []
    visited[vertex] = False
for edge in T:
    s,t = edge
    family_dict[s].append(t)
    family_dict[t].append(s)
    
#print ("parents/children of Ginger:",family_dict['Ginger'])
#print (family_dict)

Q = deque()
Q.append(root)


while len(Q)>0:
    node = Q.popleft()
    children = family_dict[node]
    if not visited[node]:
        visited[node] = True
        for child in children:
            if not visited[child]:
                tree[node].append(child)
                Q.append(child)

print (tree)

{'Norm': ['Yaakov'], 'Yaakov': [], 'Jeff': ['Vince'], 'Peter': ['Wanda'], 'Vince': [], 'Mabel': ['Ursala'], 'Ursala': [], 'Bob': ['Eve', 'Luis', 'Alice', 'Mabel'], 'Sarah': [], 'Ginger': ['Norm', 'Sarah'], 'Queen': [], 'Irene': ['Tom'], 'Zandra': [], 'Kathy': ['Queen'], 'Doug': ['Kathy'], 'Ronald': [], 'Howard': ['Oprah'], 'Frank': ['Ginger', 'Jeff'], 'Wanda': [], 'Luis': ['Ronald', 'Zandra'], 'Alice': ['Carol', 'Doug'], 'Xanthia': [], 'Oprah': ['Xanthia'], 'Carol': ['Irene', 'Peter'], 'Tom': [], 'Eve': ['Frank', 'Howard']}


Execute the following two blocks to check your result:

In [10]:
print_tree_depth_first(root,tree)

 Bob
   Eve
     Frank
       Ginger
         Norm
           Yaakov
         Sarah
       Jeff
         Vince
     Howard
       Oprah
         Xanthia
   Luis
     Ronald
     Zandra
   Alice
     Carol
       Irene
         Tom
       Peter
         Wanda
     Doug
       Kathy
         Queen
   Mabel
     Ursala


In [11]:
print_tree_breath_first(root,tree)


1 : Bob
2 : Eve	 Luis	 Alice	 Mabel
3 : Frank	 Howard	 Ronald	 Zandra	 Carol	 Doug	 Ursala
4 : Ginger	 Jeff	 Oprah	 Irene	 Peter	 Kathy
5 : Norm	 Sarah	 Vince	 Xanthia	 Tom	 Wanda	 Queen
6 : Yaakov

## Question 4: n queens problem
Backtracking is the technique of recursively exploring the tree that contains all the possible solutions to a problem. Choose a systematic way to explore all the possible cases. This approach should reflect a rooted tree, and the backtracking approach is a depth-first search of the rooted tree. Whenever the search has found a solution or determined that there are no further solutions on the branches below the current vertex, backtrack to the preceeding vertex. 

A classic example of a problem that can be easily solved with this approach is the n queens problem.  This problem is to determine all the possible ways to place n nonattacking queens on an n-by-n chess board. The following code provides two helpful routines for this problem and illustrates one of the solutions for the 4 queens problem.

In [12]:
import numpy as np

def build_chessboard(N):
    chessboard = np.zeros((N,N))
    return chessboard

def print_chessboard(chessboard):
    N = len(chessboard)
    for r in range(N):
        for c in range(N):
            if chessboard[r,c] == 1:
                print ('Q', end="")
            else:
                print ('.', end="")
        print ()
    print ()

# generate an empty 4x4 chessboard:
chessboard = build_chessboard(4)
print (chessboard)

# Place 4 non-attacking queens on this board
chessboard[1,0] = 1
chessboard[3,1] = 1
chessboard[0,2] = 1
chessboard[2,3] = 1

# Pretty print the resulting board
print_chessboard(chessboard)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
..Q.
Q...
...Q
.Q..



Complete the following code to solve the n queens problem by returning the total number of solutions while printing only the first five solutions.

In [13]:
def n_queens(_chessboard, col=0, count=0):
    """ given a partially filled <chessboard>, try to place a queen in column <col> and recursively fill the board.
    Finally return the number of solutions (added to <count>)"""
    N = len(_chessboard)
    if col == N:
        if count < 5:
            print_chessboard(_chessboard)
        count = count+1
        return count 
    for i in range(N):
        chessboard = _chessboard.copy()
        if chessboard[i,col] == 0:
            chessboard[i,col] = 1
            for j in range(N):
                if chessboard[j,col] != 1:
                    chessboard[j,col] = -1
                if chessboard[i,j] != 1:
                    chessboard[i,j] = -1
            r = i+1
            c = col+1
            while r < N and c < N:
                if chessboard[r,c] != 1:
                    chessboard[r,c] = -1
                r=r+1 
                c=c+1
            r = i-1
            c = col +1
            while r >=0 and c < N:
                if chessboard[r,c] != 1:
                    chessboard[r,c] = -1
                r=r-1 
                c=c+1
            #print()
            #print(chessboard)
            count = n_queens(chessboard, col = col+1, count = count)
            
    # Examine all available squares in column <col> (value is 0), place the queen, and 
    # mark all squares under attack by that queen (use anything except 0 or 1).
    # Note: you can make a copy of a chessboard using chessboard.copy()
    #
    
    # ????
    
    return count

chessboard = build_chessboard(5)
count = n_queens(chessboard)
print ("solutions: ", count)

Q....
...Q.
.Q...
....Q
..Q..

Q....
..Q..
....Q
.Q...
...Q.

..Q..
Q....
...Q.
.Q...
....Q

...Q.
Q....
..Q..
....Q
.Q...

.Q...
...Q.
Q....
..Q..
....Q

solutions:  10


In [14]:
def test(cb):
    cb[0,0]=1
    print_chessboard(cb)
    
chessboard = build_chessboard(4)
print_chessboard(chessboard)
test(chessboard.copy())# try chessboard.copy() instead
print_chessboard(chessboard)  # oooops!

....
....
....
....

Q...
....
....
....

....
....
....
....



In [15]:
def test(b):
    b=b+1
    print (b)
    
n = 1
print (n)
test(n)
print (n)

1
2
1


In [16]:
import copy
def test(b):
    b.append(1)
    print (b)
    
n = [1,2,3]
print (n)
test(copy.copy(n)) 
print (n)
test(n)
print (n)

[1, 2, 3]
[1, 2, 3, 1]
[1, 2, 3]
[1, 2, 3, 1]
[1, 2, 3, 1]


In [17]:
import copy
a=[]
copy.deepcopy(a)

[]

In [18]:
import copy

# copy makes a copy of the outer-most object, but keeps the same references to the inner
# object.
a=[2,4,[6]]
print ("before: a=", a)

b=copy.copy(a)
b[0]+=1
b[2][0]+=1

print ("after: a=",a," b=", b, " (using copy)")

# deepcopy also makes a copy of each contained element (recursively)
a=[2,4,[6]]
b=copy.deepcopy(a)
b[0]+=1
b[2][0]+=1
print ("after: a=",a," b=", b, " (using deepcopy)")


before: a= [2, 4, [6]]
after: a= [2, 4, [7]]  b= [3, 4, [7]]  (using copy)
after: a= [2, 4, [6]]  b= [3, 4, [7]]  (using deepcopy)
